package ccp.assignment;

import java.util.Scanner;

public class CCPAssignment {
    public static void main(String[] args) {
        Cafe cf = new Cafe();
        Customer customer = new Customer(cf);
        CupBoardEquipment ce = new CupBoardEquipment();
        Employee emp = new Employee(cf, ce);
        AutoGeneratedCustomer ac = new AutoGeneratedCustomer(cf);
        
        Thread employee = new Thread(emp);
        Thread auto = new Thread(ac);
        employee.start();
        auto.start();
        
        Clock clock = new Clock(ac,emp);
        clock.start();
        
       try{
            employee.join();
            auto.join();
            clock.join();
       }
       catch(Exception e){}
    }
}
