package ccp.assignment;

public class Clock extends Thread {
    AutoGeneratedCustomer agc;
    Employee employee;
    int timeHour = 8;
    int timeMinute;


    
    public Clock(AutoGeneratedCustomer ag, Employee e){
        employee = e;
        agc = ag;     
    }
    public String timeNow(){
        return timeHour + ":" + timeMinute;
    }
    public void run(){
        for (;timeHour < 14; timeHour++){
            System.out.println("Clock: The Time is " + timeHour + ":00");
            if (timeHour == 12){
                System.out.println("Clock: Its 1 hour before Closing Time");
                employee.owner.lastOrder();
            }
            for (timeMinute = 0; timeMinute <= 60; timeMinute = timeMinute + 10){
                try{
                    Thread.sleep(1000);  
                }
                catch(Exception e){}  
            }
        }
        agc.close();
        employee.close();
        employee.owner.servingRest();
    }
}