package ccp.assignment;

import java.util.Date;
import java.util.Random;

public class Customer implements Runnable {
    String customerName;
    AutoGeneratedCustomer acg;
    Employee e;
    Cafe cafe;
    String order;
    public Customer(Cafe cf){
        cafe = cf;
    }
    public String getCustomerName(){
        return customerName;
    }
    public String getOrder(){
        return order;
    }
    public void setCustomerName(String custName){
        customerName = custName;
    }
    public void run(){
        orderDrinks();
    }
    public synchronized void orderDrinks(){
        if(cafe.addCustomer(this)){
            int next = new Random().nextInt(2);
            if(next == 1){
                order = "Cappucino";
                System.out.println(getCustomerName() +  " Order Cappucino");
            }
            else{
                order = "FruitJuice";
                System.out.println(getCustomerName() + " Order Fruit Juice");
            }
        }
    }
}
